#!/usr/bin/env python3

import discord
import os
from dotenv import load_dotenv
import dbtools
import btools


# Load envirenment variables
load_dotenv()

# Aliases
intents = discord.Intents.all()
client = discord.Client(intents=intents)

# Specify the database folder
database = os.getcwd() + "/database"


@client.event
async def on_ready():
    print(f'Me has logged in as bot: {client.user}')
    await client.change_presence(activity=discord.Game('with your Mother'))


@client.event
async def on_message(message):
    msg = str(message.content)
    channel = message.channel
    user = message.author
    username = str(user).split('#')[0]
    print(username, '-', channel, ':', msg)

    if msg.lower().startswith(os.getenv('PREFIX')):
        # Check if there are arguments for the command
        spacecount = btools.char_counter(msg, ' ')
        if spacecount == 0:
            fullcmd = msg
            arguments = "N/A"
        else:
            fullcmd, arguments = msg.split()
        command = btools.remove_chars(fullcmd, os.getenv('PREFIX'))
        # Legacy Code
        #if dbtools.legcommandfinder(command):
        #    cmdexec = 'cod.' + command
        #    cmdexec(command, arguments, channel, user, username, client, discord)
        if dbtools.cmdquery(command, database + '/commands.json'):
            await btools.command_maker(command, arguments, channel, user, username, client, discord)

client.run(os.getenv('TOKEN'))
